spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()zyxwvutsrqponmlkjihgfedcba1234567890
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.keanntech.framework.**.domain
mybatis-plus:
  mapper-locations: classpath*:mybatis/*Mapper.xml

keanntech:
  apiPathWhiteConfig:
    - /favicon.ico
    - /**/*.css
    - /**/*.js
    - /**/*.png
    - /**/*.gif
    - /**/*.ttf
    - /v3/**
    - /v2/api-docs
    - /swagger-ui/**
    - /swagger-resources/**
    - /swagger-resources/configuration/ui
    - /swagger-resources
    - /swagger-resources/configuration/security
    - /swagger-ui.html
    - /doc.html
    - /webjars/**
    - /api/admin/v1/login
  tenant:
    header: tenantCode
  table-pre: t_keann_